//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRW
{
    using System;
    //using System.Data.Entity;
    //using System.Data.Entity.Infrastructure;
    
    //public partial class Entities : DbContext
    //{
    //    public Entities()
    //        : base("name=Entities")
    //    {
    //    }
    
    //    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    //    {
    //        throw new UnintentionalCodeFirstException();
    //    }
    
    //    public virtual DbSet<Categories> Categories { get; set; }
    //    public virtual DbSet<Laboratories> Laboratories { get; set; }
    //    public virtual DbSet<Product> Product { get; set; }
    //    public virtual DbSet<Tests> Tests { get; set; }
    //    public virtual DbSet<Used_Enviroments> Used_Enviroments { get; set; }
    //    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    //    public virtual DbSet<User> User { get; set; }
    //}
}
