//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Used_Enviroments
    {
        public Used_Enviroments()
        {
            this.Tests = new HashSet<Tests>();
        }
    
        public int id_UsedE { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Tests> Tests { get; set; }
    }
}
